framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: '%env(APP_MAILER_FROM)%'
            recipients: ['%env(APP_MAILER_TO)%']
        headers:
            From: '%env(APP_MAILER_FROM)%'
            To: '%env(APP_MAILER_TO)%'
