services:
    php-fpm:
        container_name: temperature-php-fpm
        build: 
            context: docker
            dockerfile: Dockerfile-php-fpm
        restart: always
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - 9000:9000
        links:
            - mariadb
            - redis
            - mail
        depends_on:
            - mariadb
            - nginx
            - mail
            - redis
            
    nginx:
        container_name: temperature-nginx
        image: nginx:latest
        restart: always
        working_dir: /app
        volumes:
            - .:/app
            - ./docker/etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        environment:
            - NGINX_HOST=temperature.local.paginaemconstrucao.com.br
            - NGINX_PORT=80
            
    mariadb:
        container_name: temperature-mariadb
        image: mariadb:latest
        restart: always
        working_dir: /app
        ports:
            - 3306:3306
        environment:
            - MARIADB_ROOT_PASSWORD=temperature
            - MARIADB_USER=temperature
            - MARIADB_PASSWORD=temperature
            - MARIADB_DATABASE=temperature
        volumes:
            - type: volume
              source: mariadb
              target: /var/lib/mysql
            - .:/app
            
    phpmyadmin:
        container_name: temperature-phpmyadmin
        image: phpmyadmin:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=temperature
            - MYSQL_USER=temperature
            - MYSQL_PASSWORD=temperature
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=temperature
            - PMA_PASSWORD=temperature
            - PMA_PMADB=temperature
#            - PMA_ARBITRARY=0
        ports:
            - 8080:80
        depends_on:
            - mariadb
        links:
            - mariadb:db

    mail:
        container_name: temperature-mail
        image: mailhog/mailhog:latest
        restart: always
        ports:
            - 8025:8025
            - 1025:1025

    redis:
        container_name: temperature-redis
        image: redis:latest
        restart: always
        ports:
            - 6379:6379

volumes:
    mariadb:
