app_city_index:
    path: /
    controller: App\Controller\CityController::index
    methods: GET|POST
    defaults:
        country: null
        state: null

app_city_states:
    path: /states
    controller: App\Controller\CityController::statesJson
    methods: POST

app_city_select:
    path: /select/{cityId}
    controller: App\Controller\CityController::selectCity
    methods: GET
    requirements:
        cityId: '\d+'

