app_configuration_index:
    path: /
    controller: App\Controller\ConfigurationController::index
    methods: GET

app_configuration_new:
    path: /new
    controller: App\Controller\ConfigurationController::new
    methods: GET|POST

app_configuration_show:
    path: /{id}
    controller: App\Controller\ConfigurationController::show
    methods: GET
    requirements:
        id: '[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}'

app_configuration_edit:
    path: /{id}/edit
    controller: App\Controller\ConfigurationController::edit
    methods: GET|POST
    requirements:
        id: '[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}'

app_configuration_delete:
    path: /{id}
    controller: App\Controller\ConfigurationController::delete
    methods: POST
    requirements:
        id: '[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}'
