app_country_index:
    path: /
    controller: App\Controller\CountryController::index
    methods: GET

app_country_new:
    path: /new
    controller: App\Controller\CountryController::new
    methods: GET|POST

app_country_show:
    path: /{id}
    controller: App\Controller\CountryController::show
    methods: GET
    requirements:
        id: '[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}'

app_country_edit:
    path: /{id}/edit
    controller: App\Controller\CountryController::edit
    methods: GET|POST
    requirements:
        id: '[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}'

app_country_delete:
    path: /{id}
    controller: App\Controller\CountryController::delete
    methods: POST
    requirements:
        id: '[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}'
