FROM php:fpm

RUN apt update -y

RUN apt install -y libicu-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libonig-dev

RUN docker-php-ext-install intl

RUN docker-php-ext-install pdo

RUN docker-php-ext-install pdo_mysql

RUN docker-php-ext-install gd

RUN docker-php-ext-install mbstring

ADD ./etc/php-fpm/php.ini-production /usr/local/etc/php/php.ini

WORKDIR /app