#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

#[Route('/temperature', name: 'app_temperature')]
index:
    path: /
    controller: App\Controller\TemperatureController::index
    methods: GET
