name: "Tux"
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Obter código"
        uses: actions/checkout@v4        
      - name: "Copiar código"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TUX_HOST }}
          port: ${{ secrets.TUX_SSH_PORT }}
          username: ${{ secrets.TUX_USERNAME }}
          key: ${{ secrets.TUX_SSH_PRIVATE_KEY }}
          source: "."
          target: "/deploy/temperature"
      - name: "Construção da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TUX_HOST }}
          username: ${{ secrets.TUX_USERNAME }}
          key: ${{ secrets.TUX_SSH_PRIVATE_KEY }}
          port: ${{ secrets.TUX_SSH_PORT }}
          script: |            
            cd /deploy/temperature
            composer install --no-dev --no-progress -a -o
            composer dump-env prod
            sudo cp -RTf /deploy/temperature/ /var/www/temperature
            cd /var/www/temperature
            APP_ENV=prod APP_DEBUG=0 sudo php bin/console cache:clear -q -n
            sudo rm -R public/assets
            APP_ENV=prod APP_DEBUG=0 sudo php bin/console asset-map:compile
            sudo chown -R www-data: .
